// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravianTools.DAL;

namespace TravianTools.DAL.Migrations
{
    [DbContext(typeof(TravianToolsContext))]
    partial class TravianToolsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7");

            modelBuilder.Entity("TravianTools.DAL.NeighborsVillageInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("PointX")
                        .HasColumnType("TEXT");

                    b.Property<string>("PointY")
                        .HasColumnType("TEXT");

                    b.Property<string>("UntilProtectionTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NeighborsVillageInfos");
                });

            modelBuilder.Entity("TravianTools.DAL.StateConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Configs");
                });
#pragma warning restore 612, 618
        }
    }
}
